Increased coverage for app component from 31% to 77%
shubham-kumar10/yummy-bites pull request #14
Opened 2020-10-18 18:36 UTC by AlexandreInsua

Hi, I was working in unit tests.
I have left two commented tests in case you want to do the refactorings that would be necessary for the app to pass them.
I would like to continue working on this project.
Could I keep writing tests?

2020-10-19 17:59 UTC, shubham-kumar10 requested changes
Sure, please continue. I have starting writing test for item-edit component, please take it up after I commit it. For other components please feel free to continue.

2020-10-19 17:59 UTC, shubham-kumar10 commented on package.json
> +}
@AlexandreInsua Can you please remove package.json and package-lock.json from the commit?

2020-10-19 18:58 UTC, AlexandreInsua commented
Done.

2020-10-19 21:21 UTC, merged

2020-10-20 20:23 UTC, AlexandreInsua commented
Hi, @shubham-kumar10 .  I go to write tests for signup component.